version: '2.3'

services:
  one:
    image: alpine:latest
    command: sh -c "echo new && sleep infinity"
    stop_signal: SIGKILL
    networks:
      - default

networks:
  default:
    driver: bridge
    ipam:
      config:
        - gateway: '192.168.91.1'
          subnet: '192.168.91.0/24'
      driver: default